version: "3.9"

services:
  db:
    image: db
    container_name: db
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
